export const CONTENT_REQUEST = 'CONTENT_REQUEST'
export const CONTENT_SUCCESS = 'CONTENT_SUCCESS'
export const CONTENT_FAILURE = 'CONTENT_FAILURE'

export const CONTENT_RANK_REQUEST = 'CONTENT_RANK_REQUEST'
export const CONTENT_RANK_SUCCESS = 'CONTENT_RANK_SUCCESS'
<<<<<<< HEAD
export const CONTENT_RANK_FAILURE = 'CONTENT_RANK_FAILURE'
=======
export const CONTENT_RANK_FAILURE = 'CONTENT_RANK_FAILURE'

export const CONTENT_TAGS_SUCCESS = 'CONTENT_RANK_SUCCESS'
>>>>>>> 99d60a747d6c61904d32ff07596ab0cbc5b7a781
