export const MENU_REQUEST = 'MENU_REQUEST';
export const MENU_SUCCESS = 'MENU_SUCCESS';

//artcile
export const CONTENT_REQUEST = 'CONTENT_REQUEST';
export const CONTENT_SUCCESS = 'CONTENT_SUCCESS';
export const CONTENT_FAILURE = 'CONTENT_FAILURE';

//hotest artcile
export const CONTENT_RANK_REQUEST = 'CONTENT_RANK_REQUEST';
export const CONTENT_RANK_SUCCESS = 'CONTENT_RANK_SUCCESS';
export const CONTENT_RANK_FAILURE = 'CONTENT_RANK_FAILURE';

//tags
export const CONTENT_TAGS_SUCCESS = 'CONTENT_TAGS_SUCCESS';

//artcile detail
export const CONTENT_ARTICLE_SUCCESS = 'CONTENT_ARTICLE_SUCCESS';

//USERINFO
export const USERINFO_REQUEST = 'USERINFO_REQUEST';
export const USERINFO_SUCCESS = 'USERINFO_SUCCESS';
export const USERINFO_FAILURE = 'USERINFO_FAILURE';

//TOKEN
export const TOKEN_REQUEST = 'TOKEN_REQUEST';
export const TOKEN_SUCCESS = 'TOKEN_SUCCESS';
export const TOKEN_FAILURE = 'TOKEN_FAILURE';

//TOKEN REFRESH
export const TOKEN_REFRESH_REQUEST = 'TOKEN_REFRESH_REQUEST';
export const TOKEN_REFRESH_SUCCESS = 'TOKEN_REFRESH_SUCCESS';
export const TOKEN_REFRESH_FAILURE = 'TOKEN_REFRESH_FAILURE';
